version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  app:
    build: .
    container_name: notification
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: >
      uvicorn app.server.app:app --host 0.0.0.0 --port 8000

volumes:
  mongodb:
